apiVersion: v1
kind: Service
metadata:
  name: kubernetes-dashboard-kong-proxy
  namespace: kubernetes-dashboard
spec:
  selector:
    app: kubernetes-dashboard-kong
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443