version: "3"

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - "3306:3306"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      MYSQL_DATABASE: social-media-database
      MYSQL_USER: social-media-user
      MYSQL_PASSWORD: dummypassword
      MYSQL_ROOT_PASSWORD: dummypassword







